"""
qfte_engine/mvp.py
==================
QFTE V23.0 — Moteur principal (football)
Version propre - sans doublon
"""

import math
from qfte_engine.utils import (
    parse_matchs, parse_hcp, parse_ou, parse_ml,
    parse_total_mt, parse_quart, ff, fi, bloc_candidat
)

try:
    from qfte_engine.signature_foot import analyser_signature_foot, calculer_over_under_avec_ic
except Exception:
    analyser_signature_foot = None
    calculer_over_under_avec_ic = None

try:
    from qfte_engine.forensics import analyser_market_forensics, ajuster_fiabilite
except Exception:
    analyser_market_forensics = None
    ajuster_fiabilite = None

try:
    from qfte_engine.stacking import analyser_meta_ensemble, ajuster_fiabilite_pcs
except Exception:
    analyser_meta_ensemble = None
    ajuster_fiabilite_pcs = None

try:
    from qfte_engine.cross_market import analyser_cross_market, ajuster_fiabilite_consistency
except Exception:
    analyser_cross_market = None
    ajuster_fiabilite_consistency = None

try:
    from qfte_engine.regime import analyser_regime
except Exception:
    analyser_regime = None

try:
    from qfte_engine.time_decay import extraire_moyennes_ponderees, fusion_ponderee
except Exception:
    extraire_moyennes_ponderees = None
    fusion_ponderee = None

SEUIL_FIABILITE = 0.75
SEUIL_VALUE_1X2 = 0.05
SEUIL_CONFIANCE = 0.70
EPS = 1e-9

def _safe_float(value, default=0.0):
    ...
def _clamp(value, minimum=0.0, maximum=1.0):
    ...
def _safe_list(value):
    ...
def moy(values, default=0.0):
    ...
def poisson_pmf(k, lam):
    ...

def compute_score_matrix(lambda_home, lambda_away, max_goals=8): ...
def compute_1x2(matrix): ...
def compute_ratio_ht(x): ...
def demargeage_proportionnel(cote_1, cote_x, cote_2): ...
def proba_handicap_dom(matrix, handicap=0.0): ...
def proba_handicap_ext(matrix, handicap=0.0): ...

def facteur_meteo(meteo): ...
def facteur_enjeu(enjeu): ...
def facteur_blessures(value): ...
def facteur_fatigue(value): ...
def facteur_classement(pos_dom=None, pos_ext=None, total_equipes=None): ...
def facteur_forme_recente(matchs, domicile=True): ...
def facteur_h2h(h2h): ...

def compute_ev(probabilite, cote): ...
def compute_reliability(probabilite, cote=0.0): ...
def compute_stake(ev, fiabilite, confiance=1.0): ...
def classify_decision(ev, fiabilite, probabilite): ...
def appliquer_filtres_discipline(candidat): ...
def eval_candidat_simple(marche, selection, probabilite, cote=None, ligne=None, direction=None): ...
def appliquer_forensics_au_candidat(candidat, forensics=None): ...
def appliquer_stacking_au_candidat(candidat, stacking=None): ...
def appliquer_consistency_au_candidat(candidat, cross_market=None): ...

def calcul_handicap_complet(matrice, hcp_dom, hcp_ext=None, cote_dom=None, cote_ext=None): ...
def calcul_ou_poisson(lambda_total, ligne): ...
def calcul_marches_2mt(...): ...
def detecter_divergences(...): ...
def _normaliser_matchs(matchs): ...
def _fusionner_historiques(contextuel, global_): ...
def _extraire_buts(matchs, domicile=True): ...
def _estimer_lambda_equipe(matchs, moyenne_def_adverse=None, domicile=True): ...
def _extraire_ligne_et_cotes(structure, default_line=None): ...
def _construire_ou_resultats(lambda_total, ou_lignes): ...
def _normaliser_candidats(candidats, forensics=None, stacking=None, cross_market=None): ...
def _appel_module(fonction, *args, default=None, **kwargs): ...
def _selectionner_meilleur_candidat(candidats): ...

def analyser_match_football(
    home_ctx, home_glob, away_ctx, away_glob,
    cote_1, cote_x, cote_2,
    cote_1_ouverture, cote_x_ouverture, cote_2_ouverture,
    meteo="normale", enjeu="normal",
    blessures_dom=False, blessures_ext=False,
    fatigue_dom=False, fatigue_ext=False,
    h2h=None, hcp_lignes=None, ou_lignes=None,
    pos_dom=None, pos_ext=None, total_equipes=None,
    reserve_1=None, reserve_2=None, ligue=None,
):
    ...
    return resultat
